name: Report failures to Slack

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "* * * * *"

jobs:
  write-results:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report to Slack
        uses: ./
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          workflow-results: "success,failed"
          owner-name: dwardu89
