name: Report failures to Slack

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  write-results:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Report to Slack
        uses: ./
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          workflow-results: "failed"
          owner-name: dwardu89
